future4code/Vaughan-pokedex1

pokedex1/src/App.js
pokedex1/src/components/PokemonCard/PokemonCard.js
pokedex1/src/components/PokemonCard/styled.js
pokedex1/src/pages/HomePage/HomePage.js

feito card

---

pokedex1/src/App.js
pokedex1/src/pages/Details/Details.js

só criei a página de detalhes

---

pokedex1/src/components/PokemonCard/PokemonCard.js
pokedex1/src/hooks/useRequestData.js
pokedex1/src/pages/Details/Details.js

fotinhos do pokemon estão aparecendo!

---

pokedex1/src/components/Header/styled.js
pokedex1/src/components/PokemonCard/PokemonCard.js
pokedex1/src/routers/coordenation.js

feito botao pra ir pra pagina de detalhes

---

pokedex1/src/components/PokemonCard/PokemonCard.js
pokedex1/src/pages/Home/HomePage.js
pokedex1/src/pages/Pokedex/Pokedex.js

Implement props pokemonCard button

---

pokedex1/src/App.js
pokedex1/src/components/PokemonCard/PokemonCard.js
pokedex1/src/global/GlobalState.js
pokedex1/src/global/GlobalStateContext.js
pokedex1/src/hooks/useRequestData.js
pokedex1/src/pages/Details/Details.js

feito estado global

---

pokedex1/src/components/PokemonCard/PokemonCard.js

Maldito GitHub

---

pokedex1/src/pages/Details/Details.js
pokedex1/src/pages/Details/styled.js

página de detalhes com informações, falta estilizar

---

pokedex1/src/pages/Details/Details.js
pokedex1/src/pages/Details/styled.js

Background da página de detalhes

---

pokedex1/package-lock.json
pokedex1/package.json
pokedex1/src/App.js
pokedex1/src/components/PokemonCard/PokemonCard.js
pokedex1/src/components/PokemonCard/styled.js
pokedex1/src/global/GlobalState.js
pokedex1/src/hooks/useRequestData.js
pokedex1/src/pages/Details/Details.js

paginacao feita

---

pokedex1/src/App.js
pokedex1/src/components/PokemonCard/PokemonCard.js
pokedex1/src/components/PokemonCard/styled.js
pokedex1/src/constants/theme.js
pokedex1/src/global/GlobalState.js

GitHub me ajuda

---

pokedex1/src/components/PokemonCard/PokemonCard.js
pokedex1/src/pages/Details/Details.js
pokedex1/src/pages/Details/styled.js

Gabi gabi h

---

pokedex1/src/pages/Details/Details.js
pokedex1/src/pages/Details/styled.js

mudei o degradê do fundo dos detalhes. Tirei os moves por enquanto.

---

pokedex1/src/components/PokemonCard/PokemonCard.js
pokedex1/src/components/PokemonCard/styled.js
pokedex1/src/constants/theme.js
pokedex1/src/hooks/useRequestData.js
pokedex1/src/pages/Home/HomePage.js
pokedex1/src/pages/Pokedex/Pokedex.js

batalha feitaa aeeowowow ihgaaaaaa

---

pokedex1/src/components/PokemonCard/PokemonCard.js

nome dos pokemons colocado no alert da batalha

---

pokedex1/src/components/PokemonCard/PokemonCard.js
pokedex1/src/global/GlobalState.js
pokedex1/src/pages/Home/HomePage.js
pokedex1/src/pages/Pokedex/Pokedex.js

button e background

---

pokedex1/public/index.html
pokedex1/src/App.js
pokedex1/src/components/Header/Header.js
pokedex1/src/components/Header/styled.js
pokedex1/src/components/PokemonCard/PokemonCard.js
pokedex1/src/components/PokemonCard/styled.js
pokedex1/src/global/GlobalState.js
pokedex1/src/global/GlobalStateContext.js
pokedex1/src/pages/Details/Details.js
pokedex1/src/pages/Home/HomePage.js
pokedex1/src/pages/Pokedex/Pokedex.js

tirei os console.logs e arrumei um pouco a responsividade

---

pokedex1/src/pages/Details/styled.js

responsividade página de detalhes feita

---

pokedex1/src/pages/Details/Details.js

debugado key

---

pokedex1/src/components/PokemonCard/PokemonCard.js
pokedex1/src/components/PokemonCard/styled.js
pokedex1/src/global/GlobalState.js

tirado os alerts da batalha

---

pokedex1/src/components/PokemonCard/PokemonCard.js

debugado loading
